name: franklab_mountainsort
channels:
- conda-forge
- flatiron
- defaults
- franklab
dependencies:
- mountainlab
- mountainlab_pytools
- ml_ephys
- ml_pyms
- ml_ms4alg
- ml_ms3
- qt-mountainview
- franklab_msdrift
- franklab_mstaggedcuration
- jupyter
- jupyterlab
- nb_conda
- pandas
- dask
- pytest-cov
- coveralls
- setuptools
- "python >= 3.6"
- pip
- pip:
  - nb-black
